### ISSUE TITLE
Extenson is unable to connect with Desktop APP

### ISSUE THREAD

**Issue by GamerClassN7** [keeweb/keeweb-connect#19]
Hi,
 just saw in latest update there is new super useful native browser integration. 
unfortunately for me it is not working :(

Integration wersion 0.3.6
![image](https://user-images.githubusercontent.com/22167469/120142903-70d7f100-c1df-11eb-8f23-71bdd2822e4d.png)

KeeWeb version  v1.18.6
![image](https://user-images.githubusercontent.com/22167469/120142935-7f260d00-c1df-11eb-91c8-5f04debfead1.png)

Thank you for any help you can provide.

Best Regards
JonatanRek

**Comment by antelle** [comment]
Hi! What is your browser and OS?

**Comment by GamerClassN7** [comment]
Browser:
- Google Chrome v0.3.6
OS is Windows:
- Microsoft Windows 10 Enterprise - 10.0.19043 N/A Build 19043

**Comment by antelle** [comment]
What is Chrome v0.3.6?

**Comment by GamerClassN7** [comment]
Sorry v0.3.6 vas version of extension.
so 
Google Chrome is  version 91.0.4472.77 (Oficiální sestavení) (64bitový)

**Comment by antelle** [comment]
I see. Let's check the background page of the extension. You can see it in chrome://extensions, click "inspect" there.

**Comment by GamerClassN7** [comment]
Can you send any screenshot so i can see what you mean ? i cans see inspect anywhere :(

**Comment by GamerClassN7** [comment]
Or did you mean that HTML page with setting ?
![image](https://user-images.githubusercontent.com/22167469/120218101-8a0d8b80-c239-11eb-95af-6cacd06e91e3.png)

**Comment by antelle** [comment]
No, not the options page. This page: https://i.stack.imgur.com/MSVxw.png

**Comment by GamerClassN7** [comment]
i dont hawe anything like this, there :(
![image](https://user-images.githubusercontent.com/22167469/120219643-d4900780-c23b-11eb-8cc7-390a398ecd96.png)

**Comment by GamerClassN7** [comment]
BTW i am not he Clever Person but also not a Dummes one :) i try to google it but i was not able to access the site :)

**Comment by antelle** [comment]
If you click "details" in KeeWeb connect, there will be an option inside.

**Comment by GamerClassN7** [comment]
For anyone who will be strandet like me 
1) Go to: "chrome://extensions"
2) Click enable "Dev Mode"
![image](https://user-images.githubusercontent.com/22167469/120220000-5b44e480-c23c-11eb-88d4-7b6acda7e318.png)
3) now you will see desired link in each extension box
![image](https://user-images.githubusercontent.com/22167469/120220051-7152a500-c23c-11eb-9cee-1cb815a0c5f7.png)

**Comment by antelle** [comment]
Thanks! Didn't know that it was not visible not in dev mode.

**Comment by GamerClassN7** [comment]
Updated the post :)

**Comment by antelle** [comment]
Interesting, it looks like the native messaging host crashes or prints some error. 
Let's try launching it manually. It should be located next to KeeWeb.exe. You can launch it like this:
```
keeweb-native-messaging-host.txt keeweb-connect@keeweb.info
```
It's not expected to print anything, but KeeWeb should show something about a new connection in its devtools. KeeWeb devtools can be opened from Settings / General / Advanced (in the bottom).

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/120220777-8f6cd500-c23d-11eb-9d5c-4ec04b89979f.png)

**Comment by antelle** [comment]
I think it's because of PowerShell, it doesn't like `@` in arguments. Let's try it like this, maybe this will help (I don't have Windows right now to try): 
```
keeweb-native-messaging-host.exe "keeweb-connect@keeweb.info"
```

**Comment by GamerClassN7** [comment]
![image](https://user-images.githubusercontent.com/22167469/120221074-0c984a00-c23e-11eb-9369-ead270eaf6d8.png)
![image](https://user-images.githubusercontent.com/22167469/120221088-1326c180-c23e-11eb-8964-d74f08de73cf.png)

**Comment by antelle** [comment]
I see, that's the issue. The native host cannot connect to KeeWeb and it just quits. I don't understand why this happens though, it's the first time I see that it quits without printing any error. I can check where we're missing logging and rebuild it. Is this x64 or 32-bit Windows?

**Comment by GamerClassN7** [comment]
x64

**Comment by GamerClassN7** [comment]
What is starting the host Extension or Desktop app  ?

**Comment by antelle** [comment]
It's the extension who starts it: there's a mechanism in Chrome and other browsers that allows to start a so-called native host, an application registered for this extension.

**Comment by antelle** [comment]
What happens if you close KeeWeb and launch the native host in the same way?
I just tried doing it from PowerShell on Windows like you did, and it seems to work.

**Comment by GamerClassN7** [comment]
Nothing same

**Comment by antelle** [comment]
Let's make sure we can see the error if it exists. What happens if you start it without `"keeweb-connect@keeweb.info"`? It's expected to print:
```
Expected origin
```

**Comment by GamerClassN7** [comment]
NOthink output is nothing

**Comment by antelle** [comment]
Ok, so we just don't see the output in case of errors. Let's try launching it from cmd, maybe it will help?

**Comment by GamerClassN7** [comment]
i het this error 
![image](https://user-images.githubusercontent.com/22167469/120223593-1c199200-c242-11eb-8007-b8315199009a.png)

**Comment by antelle** [comment]
This explains everything, thanks. It's Visual C++ Runtime DLL that is missing. I'll check why.

**Comment by GamerClassN7** [comment]
I downloaded and installed https://support.microsoft.com/cs-cz/topic/posledn%C3%AD-podporovan%C3%A1-verze-aplikace-visual-c-ke-sta%C5%BEen%C3%AD-2647da03-1eea-4433-9aff-95f26a218cc0 now it is working like charm :) Thank You for showing me the correct troubleshooting path :)

**Comment by GamerClassN7** [comment]
Jus a one more question why i am getting so much entries if path is fitting only for one ?
![image](https://user-images.githubusercontent.com/22167469/120224068-fccf3480-c242-11eb-9667-d33484e4b298.png)

[HOST]/dev-tools-v4/public/login

Shouldn't it be filtered by URL  ?

**Comment by antelle** [comment]
Right, downloading it manually should also work (but it's not supposed to be like that, I'll fix this).

Filtering works like this:
1. it tries to find a best match using url and path
2. if there's only one match, it will be entered directly
3. if there are multiple matches, it shows a window where it filters by domain including subdomains

**Comment by antelle** [comment]
Fixed it, next version of KeeWeb will work without additional components. Thanks for the debugging!

**Comment by GamerClassN7** [comment]
> * ere's only one match, it will be entered directly
> * if there are multiple matches, it shows a window where it filters by domain including subdomains

Nice but would be possible to incorporate some sort of featrue  for URL it selve ? 

like for example ve have 1 dev server with multiple applications is eparet folders:
[HOST]/app1
[HOST]/app2

an i have like 50 Logins for one specific URL eve that database have only one entry for app 1

I would sugest to use some Regexp like option for filtering so 
for example Entry for url [HOST]/app1/login
wil be only matched by

**Comment by antelle** [comment]
Yes I understand what you mean, and I also understand the need for it, thank you for describing it! 
It was also reported previously here: https://github.com/keeweb/keeweb/issues/1693, eventually KeeWeb will support it.

**Comment by GamerClassN7** [comment]
Hi, just reinstalled computer and error still ocure, it would be nice in main page that package up is requires, it took mi like 30minutes before i  find correct one
